In [1]:
import pandas
df = pandas.DataFrame([[2,3,5,6],[10,28,20,60]])
print(df)

    0   1   2   3
0   2   3   5   6
1  10  28  20  60


In [1]:
import os

In [2]:
os.listdir()
import pandas

In [12]:
df1 = pandas.read_csv('supermarkets.csv')
df1
import xlrd

In [10]:
df2 = pandas.read_json("supermarkets.json")
df2

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [4]:
df3 = pandas.read_excel("supermarkets.xlsx", sheet_name=0, engine='openpyxl')
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [6]:
df4 = pandas.read_csv("supermarkets-commas.txt")
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [18]:
df5 = pandas.read_csv('supermarkets-semi-colons.txt',sep=';')
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [20]:
df5.set_index('ID', inplace=True)
df5

Address           City             State Country          Name  \
ID                                                                           
1      3666 21st St  San Francisco          CA 94114     USA       Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA   Super River   
4      3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA       Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [21]:
df5.loc['2':'3',"City":"Name"]

City             State Country          Name
ID                                                       
2   San Francisco          CA 94119     USA   Bready Shop
3   San Francisco  California 94114     USA   Super River

In [23]:
df5.iloc[1:3,0:3]

Address           City             State
ID                                                 
2   735 Dolores St  San Francisco          CA 94119
3      332 Hill St  San Francisco  California 94114

In [25]:
df5

Address           City             State Country          Name  \
ID                                                                           
1      3666 21st St  San Francisco          CA 94114     USA       Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA   Super River   
4      3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA       Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [33]:
df5.drop(1,0)

Address           City             State Country          Name  \
ID                                                                           
2    735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA   Super River   
4      3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA       Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

    Employees  
ID             
2          15  
3          25  
4          10  
5          12  
6          20

In [34]:
df5['continent'] = df5.shape[0]*['North America']

In [35]:
df5

Address           City             State Country          Name  \
ID                                                                           
1      3666 21st St  San Francisco          CA 94114     USA       Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA   Super River   
4      3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA       Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

    Employees      continent  
ID                            
1           8  North America  
2          15  North America  
3          25  North America  
4          10  North America  
5          12  North America  
6          20  North America

In [36]:
df5['continent'] = df5['Country']+", "+df5['continent']

In [37]:
df5
# from geopy.geocoders import ArcGIS
# nom = ArcGIS()

Address           City             State Country          Name  \
ID                                                                           
1      3666 21st St  San Francisco          CA 94114     USA       Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA   Super River   
4      3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA       Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

    Employees           continent  
ID                                 
1           8  USA, North America  
2          15  USA, North America  
3          25  USA, North America  
4          10  USA, North America  
5          12  USA, North America  
6          20  USA, North America

In [39]:
from geopy.geocoders import ArcGIS
nom = ArcGIS()
df = pandas.read_csv('supermarkets.csv')
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [41]:
df['Whole Address'] = df['Address']+', '+df['City']+', '+df['State']
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                 Whole Address  
0          8         3666 21st St, San Francisco, CA 94114  
1         15       735 Dolores St, San Francisco, CA 94119  
2         25  332 Hill St, San Francisco, California 94114  
3         10         3995 23rd St, San Francisco, CA 94114  
4         12    1056 Sanchez St, San Francisco, California  
5         20      551 Alvarado St, San Francisco, CA 94114

In [42]:
df['Coords']=df['Whole Address'].apply(nom.geocode)
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                 Whole Address  \
0          8         3666 21st St, San Francisco, CA 94114   
1         15       735 Dolores St, San Francisco, CA 94119   
2         25  332 Hill St, San Francisco, California 94114   
3         10         3995 23rd St, San Francisco, CA 94114   
4         12    1056 Sanchez St, San Francisco, California   
5         20      551 Alvarado St, San Francisco, CA 94114   

                                              Coords  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [44]:
df.Coords[0]

Location(3666 21st St, San Francisco, California, 94114, (37.756648011392286, -122.42937496976432, 0.0))

In [49]:
df['latitude']=df['Coords'].apply(lambda x: x.latitude if x!= None else None)
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                 Whole Address  \
0          8         3666 21st St, San Francisco, CA 94114   
1         15       735 Dolores St, San Francisco, CA 94119   
2         25  332 Hill St, San Francisco, California 94114   
3         10         3995 23rd St, San Francisco, CA 94114   
4         12    1056 Sanchez St, San Francisco, California   
5         20      551 Alvarado St, San Francisco, CA 94114   

                                              Coords   latitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756648  
1  (735 Dolores St, San Francisco, California, 94...  37.757819  
2  (332 Hill St, San Francisco, California, 94114...  37.755875  
3  (3995 23rd St, San Francisco, California, 9411...  37.752922  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752131  
5  (551 Alvarado St, San Francisco, California, 9...  37.753511

In [50]:
import numpy

In [51]:
n=numpy.arange(27)

In [52]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [53]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
import cv2

In [56]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [58]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [59]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [62]:
img = numpy.hstack((im_g,im_g))
img

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)